### ISSUE TITLE
Add a button?

### ISSUE THREAD

**Issue by hayleox** [superlogout/superlogout.github.io#12]
Automatically logging out of every site just on loading the page is a bit annoying -- I was just sorta mindlessly clicking on a repo that someone I follow had starred, and suddenly I'm logged out of every website. It seems like it'd be nicer if you instead had to click a button to initiate the logouts.

**Comment by markasoftware** [comment]
I know this project is often used just for this purpose -- so that people can annoy their friends by logging them out from everything.

**Comment by mCzolko** [comment]
@markasoftware is right, if you want buttons, you can find them on each individual site

**Comment by Noman1237890** [comment]
I am unable to log out
